export const FETCH_WORDS_PENDING = 'FETCH_WORDS_PENDING';
export const FETCH_WORDS_FAILURE = 'FETCH_WORDS_FAILURE';
export const FETCH_WORDS_SUCCESS = 'FETCH_WORDS_SUCCESS';

export const DELETE_WORDS_PENDING = 'DELETE_WORDS_PENDING';
export const DELETE_WORDS_FAILURE = 'DELETE_WORDS_FAILURE';
export const DELETE_WORDS_SUCCESS = 'DELETE_WORDS_SUCCESS';

export const UPDATE_LIST_PENDING = 'UPDATE_LIST_PENDING';
export const UPDATE_LIST_FAILURE = 'UPDATE_LIST_FAILURE';
export const WORDS_UPDATE_SUCCESS = 'WORDS_UPDATE_SUCCESS';
export const WORDS_DELETE_SUCCESS = 'WORDS_DELETE_SUCCESS';
export const WORDS_ADD_SUCCESS = 'WORDS_ADD_SUCCESS';

export const SET_REPETITION_DATA = 'SET_REPETITION_DATA';

export const SIGN_IN = 'SIGN_IN';
export const SIGN_UP = 'SIGN_UP';
export const LOGOUT = 'LOGOUT';
