export const FETCH_WORDS_PENDING = 'FETCH_WORDS_PENDING';
export const FETCH_WORDS_FAILURE = 'FETCH_WORDS_FAILURE';
export const FETCH_WORDS_SUCCESS = 'FETCH_WORDS_SUCCESS';

export const UPDATE_LIST_PENDING = 'UPDATE_LIST_PENDING';
export const UPDATE_LIST_FAILURE = 'UPDATE_LIST_FAILURE';
export const WORDS_UPDATE_SUCCESS = 'WORDS_UPDATE_SUCCESS';
export const WORDS_DELETE_SUCCESS = 'WORDS_DELETE_SUCCESS';
export const WORDS_ADD_SUCCESS = 'WORDS_ADD_SUCCESS';